### ISSUE TITLE
fonts are not loading.

### ISSUE THREAD

**Issue by nisarhassan12** [NeonLaw/interface#455]
On latest development fonts are not loading successfully.

![image](https://user-images.githubusercontent.com/46004116/87697030-0a0a3e80-c7ab-11ea-8c2e-1e533e13bd56.png)
![image](https://user-images.githubusercontent.com/46004116/87697170-33c36580-c7ab-11ea-9bdf-119c2b75f882.png)

I can access the font file at  `localhost:8000/fonts/fonts/hk-grotesk/HKGrotesk-Medium.ttf`

I initially thought that it's due to the wrong path value specified here https://github.com/NeonLaw/interface/blob/9faae5d3a5fb510ab66bfd56688237a0e1270ece/packages/shared/src/themes/fonts.css#L3

but changing it to `/fonts/fonts/hk-grotesk/HKGrotesk-Medium.ttf` does not seem to help.

I also tried adding a new file to `packages/shared/src/fonts/` called `fonts.css` which got copied over to `packages/neon-law/static/fonts/fonts/` via the start task and then referenced it in `BaseLayout` as follows:

```jsx
<Helmet>
    <link href="/fonts/fonts/font.css" rel="stylesheet" />
</Helmet>
```
with the following contents:
```css
@font-face {
  font-family: 'HK Grotesk';
  src: url("/fonts/fonts/hk-grotesk/HKGrotesk-Regular.ttf") format("ttf");
  font-style: normal;
  font-weight: 400;
}

@font-face {
  font-family: 'HK Grotesk';
  src: url("/fonts/fonts/hk-grotesk/HKGrotesk-Regular.ttf") format("ttf");
  font-style: normal;
  font-weight: 400;
}

body {
  font-family: 'HK Grotesk';
}

```

but it did not work as expected. I verified that the `fonts.css` file is available at `localhost:8000/fonts/fonts/fonts.css` and the font file is also available at `localhost:8000/fonts/fonts/hk-grotesk/HKGrotesk-Medium.ttf`.
